### ISSUE TITLE
Display condition of action button for face image, people image, vehicle image

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#22]
Test version : V0.9.6

Currently
All actions button is always shown for face, people and vehicle image.

Expetected

When face image is selected, only Face registration button is needed.
Could you delete other buttons ?
![image](https://user-images.githubusercontent.com/102282918/165211486-aacc8134-cbf8-471e-bd84-43253feb98a0.png)

When vehicle image is selected, only Search button is needed.
Also, two option "Search for exactly similar ... " and "Search for similar.." is no need in case of vehicle.
When this button is clicked, please search with high score attribute for vehicle type and vehicle color. 

![image](https://user-images.githubusercontent.com/102282918/165211840-3eff9869-e421-476b-abc2-c839d6abf949.png)

When people image is selected,
Face registration button is shown only when the people image include "Face"

ex. People image that does not include face region
![image](https://user-images.githubusercontent.com/102282918/165212312-e6e341f6-3485-4583-b7a7-b821a4258e0c.png)

ex. People image that includes face region **and AI Face detection exists in the system (add 27th-Sep-23)**
![image](https://user-images.githubusercontent.com/102282918/165212386-edba0b81-36a5-4e46-8e54-5374cb93a8ea.png)

**Comment by EricBourque** [comment]
Ok, we fixed in 0.9.7. We assume that to check if image includes face region, we check for a value in "face_coordinate_x" when "source_type" = people

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Test result in V0.9.7 as of 13th May.

I think search button in Actions 
![image](https://user-images.githubusercontent.com/102282918/168285484-bd0efd60-5447-4cc5-abf2-20a54da44d3a.png)
can be suspended to next version develelopment if it takes more time.
(User manual should be modified if deleting this button)

**When selecting face image: OK**
![image](https://user-images.githubusercontent.com/102282918/168284648-515023f4-b580-48b2-ac0e-fe452b9834df.png)

**When selecting people image with recognizable face : not OK**
![image](https://user-images.githubusercontent.com/102282918/168284931-9cde4a6f-14ed-43f1-8ab8-52128b25aeb3.png)

Expected
![image](https://user-images.githubusercontent.com/102282918/168285027-e3871dbb-7782-4599-be23-e940b53de4df.png)


**When selecting people image without recognizable face: not OK**
![image](https://user-images.githubusercontent.com/102282918/168284840-e10c8f28-b042-4cc5-82e8-78604b372cac.png)

Expected
![image](https://user-images.githubusercontent.com/102282918/168285085-bbc0dc2f-cd38-4e6a-80ff-5afa1f15f513.png)

**When selecting vehicle image: not OK**
Display condition is OK but when clicking  
![image](https://user-images.githubusercontent.com/102282918/168285427-c6ae2029-8ed6-4eec-96bf-7c899bd28e0e.png)
, exception occurs

![image](https://user-images.githubusercontent.com/102282918/168285223-747f51a1-9c60-4aac-a601-c61563e38906.png)

************** Outer Exception **************
Exception type:System.NullReferenceException
Exception message:Object reference not set to an instance of an object.
Exception source:ActiveGuardMilestonePlugins
Exception Target Site: BK
   at ActiveGuardMilestonePlugins.Client.ActiveGuardSearch.BK(Object , RoutedEventArgs )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	5/13/2022 9:38:38 PM
Machine Name:	DESKTOP-HFH57FR
Processors count:	16
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::8520:2fdb:eeea:217e%14 (DESKTOP-HFH57FR)
Current user:	DESKTOP-HFH57FR\Admin

**Comment by EricBourque** [comment]
Fixed in new 1.0.0

**Comment by Yoshitaka-Fukushima** [comment]
Almost OK in v1.0.0 released on 18th May, but when clicking search button from Actions for vehicle image, exception error is shown.

Total 3 messages are shown. 
1st one is "Start Search Error:HandleStartActiveGuardSEarch:search id".
2nd and 3rd in Japanse mean "Start Search Error: Object reference is not set for object instance." in English.

[AGDRec_20220520_164316.zip](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/8737512/AGDRec_20220520_164316.zip)

**Comment by EricBourque** [comment]
Fixed in v1.0.0

**Comment by Yoshitaka-Fukushima** [comment]
Test result OK in V1.0.0 released on 27th May.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v1.5

In the system only AI People detection exist (AI Face detection does not exist),
when clicking "Register Face" button on Actions, exception error occurs.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/da0571ca-2656-47c2-ad89-4a7fe95bc68e)

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/a0b7f17b-0a91-4177-b662-c829a3188570)

Could you modify plug-in so that Register Face icon is not shown when AI Face detection does not exist ?
I updated condition in this ticket as follows.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/363eedd9-c390-4bad-a767-2c16e8558e46)

**Comment by EricBourque** [comment]
Fixed in 1.5.1:

-In 1.5.0, we show and hide the icons everytime user clicks on a thumbnial. We would only show the face button if:
   1. SearchResult.source_type = face
   2. SearchResult.source_type = people AND (res.SearchResult.upperbody_coordinate_x Is NOT NullOrWhiteSpace)
I believe the error was happening because we check for upperbody_coordinate_x to allow similar face search.
Now in 1.5.1, we do an additional check to see if the camera of the selected thumbnail has face application or not.
We have also applied this logic for people and vehicle and show specific error if the source_type does not match the applications on the camera. 
This error can be shown if perhaps a thumbnail exists in Active Guard, but the application has been uninstalled from the camera.
   
-If for some reason the exception occurs again, it will show a MessageBox with message instead of crashing the whole Smart Client.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Test version: v1.5.1

Partially fixed but not correct.

When two camera exists (People app for one and Face for the other),
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/6e61d6d9-7af8-46ef-8a8a-d2672718ef3b)
 
and when people image that includes clear face is selected,
"face registration button" and search option "Search for similar face" should be shown.
Previous version works well at this point.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/863c9794-aa44-4827-afdb-7fe7df023e2e)

**Comment by EricBourque** [comment]
Ok, I think I understand. This means that if there is at least 1 camera with face detection capability, and the Face = yes then we should show the face detection button.
I will update today.

**Comment by EricBourque** [comment]
Fixed in version: v1.5.2

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.5.2
