### ISSUE TITLE
"Cameras" in People watchlist does not work for new registration and update

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#36]
@EricBourque
Test version : v1.0.0 released on 27th May.

![image](https://user-images.githubusercontent.com/102282918/171529589-f66e9b45-2893-4248-b1c3-a1b9ab1400a6.png)

1. When creating new people watchlist by clicking "+" button,
   currently, no camera is selected.
   Expected, all cameras with AI People detection are selected as default.

2. When checking some cameras, click "save watchlist" and reopen setup watchlist screen,

   currently, no camera is selected. ( It looks like the settings are not reflected) for both new registration and updating for existing watchlists.

**Comment by PetrutVasile** [comment]
Fixed in the new version

**Comment by Yoshitaka-Fukushima** [comment]
Test version : V1.0.0 released on 17th, August.

Not fixed.
Camera is checked as expected but cannot register.
![image](https://user-images.githubusercontent.com/102282918/189631352-bb96c8b8-2be7-491a-abb0-b9e41ee0823d.png)


In previous version of plug-in, I remember that I can register. @EricBourque

**Comment by EricBourque** [comment]
Fixed in 1.0.1

**Comment by Yoshitaka-Fukushima** [comment]
Test version 1.0.1 released on 4th, Oct.
Almost OK, but there are minor issue.

Currently all cameras are shown as camera list in people wathclist and check box for each application does not work correctly.

![image](https://user-images.githubusercontent.com/102282918/194457421-8e9e3c8a-37b3-4f40-9c07-cda758f18056.png)

Could you show only cameras with people detection as list and delete "Find camera by features" and check box for each application ?

**Comment by EricBourque** [comment]
I believe this is solved in 1.0.1 now. Please test it.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : V1.0.1 released on 7th Oct.
Test result: not OK

When creating new people watchlist, cameras with AI People detection are checked (OK).
Then, when clicking "Save watchlist" without check or uncheck operation for camera,  no camera_ id is included in API.

![image](https://user-images.githubusercontent.com/102282918/195000317-db7a5f59-14a2-484d-adf4-0fca106270a9.png)

Once we perform check or uncheck operation for camera, API becomes correct.

**Comment by EricBourque** [comment]
Fixed in 1.0.2

**Comment by Yoshitaka-Fukushima** [comment]
Test version: v1.0.3 released on 13th,Jan.
Test result: OK
